// $Id: SSSolo.h,v 1.4 2001/08/21 02:49:29 tekhedd Exp $
// Copyright(C) 2001 Tom Surace. All rights reserved.

// SSSolo.h
//
// Generated by DriverWizard version DriverStudio 2.0.1 (Build 53)
// Requires Compuware's DriverWorks classes
//

#ifndef __SSSolo_h__
#define __SSSolo_h__

#define EOL "\n"

// Global driver trace object
extern	KDebugOnlyTrace	t;


class SSSolo : public KDriver
{
	SAFE_DESTRUCTORS
public:
	virtual NTSTATUS DriverEntry(PUNICODE_STRING RegistryPath);
	virtual NTSTATUS AddDevice(PDEVICE_OBJECT Pdo);

   void	 LoadRegistryParameters(KRegistryKey &Params);

	int	m_Unit;

	// The following data members are loaded from the registry during DriverEntry
	ULONG m_bBreakOnEntry;
	ULONG m_IsSlaveEnabled;
	ULONG m_Routing;
	ULONG m_DmaPageFrames;
	
};

#endif			// __SSSolo_h__
